name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0.x'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
      
    - name: Restore, build & publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish API
      run : dotnet publish $GITHUB_WORKSPACE/GlasgowAstro.Obsy.Api/GlasgowAstro.Obsy.Api.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
            
    - name: Deploy API
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME  }} 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
    # TODO Publish Bot
