name: pr-check.yml

on:
  pull_request:
  
env:
  DOTNET_VERSION: '6.0.x'  
  
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}       
    - name: Restore, build & publish 
      run: |
        dotnet restore
        dotnet build --configuration Release      
    - name: Test
      run: dotnet test --no-restore --verbosity normal 
